Tmi2 365/build mandatory question first page and service layer
cabinetoffice/gap-find-apply-web pull request #101
Opened 2023-10-12 16:43 UTC by a-lor-cab

## Description

[TMI2-365](https://technologyprogramme.atlassian.net/browse/TMI2-365)

Summary of the changes and the related issue. List any dependencies that are required for this change:
add mandatory-question name page with getServerSide props
add service that will be used by getServerSideProps
add skeleton for other needed pages
add routes to util
add util to determine if a page has already been answered.
add unit test coverage

## Type of change

Please check the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [√] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes:

- [√] Unit Test

- [ ] Integration Test (if applicable)

- [ ] End to End Test (if applicable)

## Screenshots (if appropriate):

Please attach screenshots of the change if it is a UI change:

# Checklist:

- [ ] If I have listed depedenencies above, I have ensured that they are present in the target branch.
- [ ] I have performed a self-review of my code.
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation where applicable.
- [ ] I have ran cypress tests and they all pass locally.

2023-10-13 14:47 UTC, ConorFayleTCO commented on packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/getServerSideProps.test.tsx
> +  });
could set up a beforeEach and afterEach to reset the env var to its original value

like
```
  let userTokenNameBackup;
  beforeEach(() => {
    jest.resetAllMocks();
    userTokenNameBackup = process.env.USER_TOKEN_NAME
    process.env.USER_TOKEN_NAME = 'gap-test';
  });
  afterEach(() => {
    process.env.USER_TOKEN_NAME = userTokenNameBackup;
  });
```

2023-10-13 16:19 UTC, ConorFayleTCO submitted a review, later dismissed

2023-10-17 09:05 UTC, ConorFayleTCO commented on packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/organisation-name.page.tsx
> +            />
don't think we need a Cancel button so should just be
```suggestion
            <Button
              text="Save and continue"
              type={ButtonTypePropertyEnum.Submit}
            />
```

2023-10-17 10:18 UTC, ConorFayleTCO commented on packages/applicant/src/pages/api/create-mandatory-question.page.tsx
> +  console.log('schemeId', schemeId);
remove

2023-10-17 10:18 UTC, ConorFayleTCO commented on packages/applicant/src/pages/api/create-mandatory-question.page.tsx
> +      'BANANA',
lol

2023-10-17 11:11 UTC, iaincooper-tco requested changes

2023-10-17 11:11 UTC, iaincooper-tco commented on packages/applicant/src/pages/mandatory-questions/[mandatoryQuestionId]/getServerSideProps.tsx
> +  }
not sure on this, that Optional is a unit test helper and we're using in live code.

2023-10-17 11:11 UTC, iaincooper-tco commented on packages/applicant/src/utils/mandatoryQuestionUtils.ts
> +};
interesting approach, I can see why you've done it as it keeps things common and gives us an entire structure journey (which explains a lot about the size of this).

2023-10-17 12:54 UTC, a-lor-cab commented on packages/applicant/src/pages/api/create-mandatory-question.page.tsx
> +      );
it was a console log, above. forgot to remove it

2023-10-17 15:47 UTC, iaincooper-tco submitted a review, later dismissed

2023-10-17 15:47 UTC, iaincooper-tco commented on packages/applicant/src/pages/api/create-mandatory-question.page.tsx
> +    console.log('e', e);
console.error

2023-10-17 15:53 UTC, iaincooper-tco approved these changes

2023-10-17 15:53 UTC, merged