TMI2-390 - Login to Spotlight from DD checks page
cabinetoffice/gap-find-apply-web pull request #158
Opened 2023-11-14 11:44 UTC by kiramarstonTCO

## Description

Ticket # and link

Summary of the changes and the related issue. List any dependencies that are required for this change:

## Type of change

Please check the relevant options.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes:

- [ ] Unit Test

- [ ] Integration Test (if applicable)

- [ ] End to End Test (if applicable)

## Screenshots (if appropriate):

Please attach screenshots of the change if it is a UI change:

# Checklist:

- [ ] If I have listed depedenencies above, I have ensured that they are present in the target branch.
- [ ] I have performed a self-review of my code.
- [ ] I have commented my code in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation where applicable.
- [ ] I have ran cypress tests and they all pass locally.

2023-11-14 13:42 UTC, iaincooper-tco requested changes

2023-11-14 13:42 UTC, iaincooper-tco commented on packages/admin/src/services/SchemeService.ts
> +};
need a test for this method

2023-11-14 14:37 UTC, kiramarstonTCO commented on packages/admin/src/services/SchemeService.ts
> +};
Done!

2023-11-16 15:41 UTC, rachelswart commented on packages/admin/src/services/SchemeService.test.ts
> +      const sessionId = 'sessionId';
These two variables could be set outside of this test because they're the same in both tests

2023-11-16 15:57 UTC, rachelswart approved these changes

2023-11-17 11:49 UTC, iaincooper-tco approved these changes

2023-11-17 12:16 UTC, merged